Matching crud
racket-puncher/back-end pull request #15
Opened 2023-11-02 11:59 UTC by nayonsoso

### 변경사항

**AS-IS**
매칭글 관련 기능 구현했습니다.
전체적인 내용은 CRUD이기 때문에 특별할 것은 없지만, 아래 내용을 유의해서 보셨으면 좋겠습니다!

사용자가 존재하지 않는 경우와 
매칭글이 존재하지 않는 경우
사용자가 만든 매칭이 아닌데 수정이나 삭제를 하려는 경우
예외를 발생시키도록 구현했습니다.

그리고 테스트 코드를 나름 열심히(?) 공부를 하며 작성을 했는데, 그 부분도 확인 부탁드립니다!

**TO-BE**

### 테스트
 
- [ ] 테스트 코드
- [ ] API 테스트

2023-11-02 16:59 UTC, younbihn approved these changes
고생하셨습니다ㅎㅎ

2023-11-02 16:59 UTC, younbihn commented on src/main/java/com/example/demo/matching/controller/MatchingController.java
> +    @GetMapping("/list")
S3..흥미롭습니당..ㅋㅎ...고생하셧어요!!!

2023-11-02 16:59 UTC, younbihn commented on src/test/java/com/example/demo/matching/controller/MatchingControllerTest.java
> +}
테스트코드 가독성 넘 좋아요~!~!~~~

2023-11-03 09:56 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/exception/impl/UserNotFoundException.java
> +        return HttpStatus.NOT_FOUND.value();
에러 코드 상세 설정 좋습니당 ㅎㅎ 저도 적용해야겠네요!

2023-11-03 09:58 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/matching/controller/MatchingController.java
> -    public ResponseEntity<MatchingDetailDto>  createMatching(
저희 포스트 mapping의 경우는 객체값을 반환하지 않기로 했으니까 HttpStatus로 반환하는 게 어떨까요? 
저는 그렇게 적용해놨습니다!

2023-11-03 10:00 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/matching/controller/MatchingController.java
> -    public ResponseEntity<MatchingDetailDto>  createMatching(
아래 똑같은 postMapping이 있네요.!! 윗 부분을 지우면 될 것 같아요 ㅎㅎ

2023-11-03 10:02 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/matching/controller/MatchingController.java
> -        return s3Uploader.uploadFile(file);
엔터 한 번 쳐주시면 좋을 것 같아요! ㅎㅎ

2023-11-03 10:04 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/matching/controller/MatchingController.java
> +        //TODO: 이미 존재하는 이미지인지 검증하는 로직이 이게 맞나..?
맞는 것 같아요! api 테스트 진행해보셨나요?

2023-11-03 10:05 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/matching/dto/MatchingPreviewDto.java
> +                .isReserved(matching.getIsReserved())
모집 마감일도 추가하면 좋을 것 같아요!

2023-11-03 10:07 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/matching/service/MatchingServiceImpl.java
> +        Matching matching = matchingRepository.save(Matching.fromDto(matchingDetailDto, siteUser));
매칭 생성할 때 종료일도 같이 저장 부탁드립니다!

2023-11-03 10:11 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/matching/service/MatchingServiceImpl.java
> +        }
참여 인원이 있는 경우 패널티 부여되는 로직이 추가되어야할 것 같습니다! 저도 TO DO 로 해놨어요! TO DO로 표시만 해두고, 패널티 부여 로직을 백엔드 회의때 논의해서 한 명이 맡으면 좋을 것 같습니다 ㅎㅎ

2023-11-03 10:12 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/matching/service/MatchingServiceImpl.java
> +        return matchingRepository.findAll(pageable)
리스트 필터링 및 정렬 부분은 아직 구현 안된 상태인거죠?

2023-11-03 10:16 UTC, hyun-Jin-Park-4808 commented on src/test/java/com/example/demo/matching/controller/MatchingControllerTest.java
> +        //then
matchingDetailDto 생성 메서드 따로 만드는 방식 좋네요 ㅎㅎ!

2023-11-03 10:18 UTC, hyun-Jin-Park-4808 requested changes
코드 잘 봤습니다. 고생 많으셨어요 :) 매칭에 마감 종료일 컬럼 추가해서 메서드에 적용하는 거랑 포스트나 패치의 경우는 상태응답만 보내는 걸로 수정하면 좋을 것 같아요!

2023-11-03 10:30 UTC, nayonsoso commented
리뷰해주셔서 감사합니다! 주신 부분들 다 수정하고있슴다~~

2023-11-03 10:31 UTC, nayonsoso commented on src/main/java/com/example/demo/matching/controller/MatchingController.java
> -    public ResponseEntity<MatchingDetailDto>  createMatching(
아 좋은 방법 같아요! 저도 그렇게 할게요👍

2023-11-03 10:31 UTC, nayonsoso commented on src/main/java/com/example/demo/matching/controller/MatchingController.java
> -        return s3Uploader.uploadFile(file);
넹!

2023-11-03 10:31 UTC, nayonsoso commented on src/main/java/com/example/demo/matching/controller/MatchingController.java
> +        //TODO: 이미 존재하는 이미지인지 검증하는 로직이 이게 맞나..?
아뇨 머지 하고나서 data.sql을 손대는 게 좋을 것 같아서 아직 안했습니다🥲

2023-11-03 10:31 UTC, nayonsoso commented on src/main/java/com/example/demo/matching/dto/MatchingPreviewDto.java
> +                .isReserved(matching.getIsReserved())
넵! 그 부분도 추가할게요!

2023-11-03 10:31 UTC, nayonsoso commented on src/main/java/com/example/demo/matching/service/MatchingServiceImpl.java
> +        return matchingRepository.findAll(pageable)
네 그 부분은 더 오래걸릴 것 같아서
우선은 필터링, 정렬 안된 기분 상태를 구현했습니다!

2023-11-03 10:31 UTC, nayonsoso commented on src/main/java/com/example/demo/matching/service/MatchingServiceImpl.java
> +        }
오 추가하겠습니다!

2023-11-03 10:36 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/matching/controller/MatchingController.java
> +        //TODO: 이미 존재하는 이미지인지 검증하는 로직이 이게 맞나..?
넵 ㅎㅎ 로직만 봤을 때는 될 것 같아요!

2023-11-03 10:37 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/matching/service/MatchingServiceImpl.java
> +        return matchingRepository.findAll(pageable)
넵 ㅎㅎ 그 부분이 제일 생각 많이 해야할 것 같아요 ㅠㅠ 수고 많으십니당 ㅠ

2023-11-06 10:17 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/entity/Matching.java
> +    @Column(name = "APPLY_NUM", columnDefinition = "INT DEFAULT 1")
엔티티에 디폴트 값 설정하면 적용 안돼요! schema.sql에만 적용하고 @DynamicInsert 어노테이션 붙여줘야 제대로 들어갑니당 ㅎㅎ

2023-11-06 10:19 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/example/demo/entity/Matching.java
> +        }
이 부분도 위와 마찬가지로 DynaimicInsert 어노테이션 붙여주면 schema.sql에서 설정한 default 값이 들어가용

2023-11-06 10:20 UTC, hyun-Jin-Park-4808 requested changes
추가 리뷰 달았습니다! 저희 중간 브랜치로 PR 다시 보내주세용!

2023-11-06 10:46 UTC, nayonsoso commented on src/main/java/com/example/demo/entity/Matching.java
> +        }
아 그렇군요 ㅎㅎ 제가 계속 시도했은데도 안들어가서 PrePersist 사용한거였는데 DynamicInsert로 수정하겠습니다!

2023-11-07 04:57 UTC, merged